-- User
CREATE TABLE "user" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  username varchar(128) NOT NULL UNIQUE,

  -- Auth
  pwd varchar(256),
  pwd_salt uuid NOT NULL DEFAULT gen_random_uuid(),
  token_salt uuid NOT NULL DEFAULT gen_random_uuid(),

  -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL  
);

-- Project
CREATE TABLE project (
  -- PK
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  -- Properties
  owner_id BIGINT NOT NULL,
  name varchar(256) NOT NULL,

  -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL  
);

-- Task
CREATE TABLE task (
  -- PK
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  -- FK
  project_id BIGINT NOT NULL,
  
  -- Properties
  title varchar(256) NOT NULL,
  done bool NOT NULL DEFAULT false,

  -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL  
);

ALTER TABLE task ADD CONSTRAINT fk_project
  FOREIGN KEY (project_id) REFERENCES project(id)
  ON DELETE CASCADE;



CREATE TABLE author (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 2000) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    bio VARCHAR(255) NOT NULL,
    -- Timestamps
cid BIGINT NOT NULL,
    ctime TIMESTAMP WITH TIME ZONE NOT NULL,
    mid BIGINT NOT NULL,
        mtime TIMESTAMP WITH TIME ZONE NOT NULL

);

CREATE TABLE publisher (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address TEXT,
    -- Timestamps
 -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL  
);

CREATE TABLE categorie (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    -- Timestamps
 -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL  
);

CREATE TABLE book (
    id  BIGINT  GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author_id INT REFERENCES author(id),
    publisher_id INT REFERENCES publisher(id),
    category_id INT REFERENCES categorie(id),
    --published_date DATE,
    isbn VARCHAR(50) UNIQUE,

-- Timestamps
 -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL  
);

CREATE TABLE borrower (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE,
    address TEXT,

-- Timestamps
 -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL  
);


CREATE TABLE book_copie (
    id SERIAL PRIMARY KEY,
    book_id INT REFERENCES book(id),
    copy_number VARCHAR(50) NOT NULL,
    is_available BOOLEAN DEFAULT TRUE,

-- Timestamps
cid BIGINT NOT NULL,
    ctime TIMESTAMP WITH TIME ZONE NOT NULL,
    mid BIGINT NOT NULL,
        mtime TIMESTAMP WITH TIME ZONE NOT NULL

);

CREATE TABLE loan (
    id SERIAL PRIMARY KEY,
    borrower_id INT REFERENCES borrower(id),
    book_copy_id INT REFERENCES book_copie(id),
    loan_date DATE NOT NULL,
    return_date DATE,

    -- Timestamps
cid BIGINT NOT NULL,
    ctime TIMESTAMP WITH TIME ZONE NOT NULL,
    mid BIGINT NOT NULL,
        mtime TIMESTAMP WITH TIME ZONE NOT NULL

)